/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void TestEmptyList() {
       LinkedList<Integer> mylist =new LinkedList<>();
        String correctresulte= mylist.toString();
        assertEquals("Null", correctresulte);

    }
    @Test void TestInsertList() {
        LinkedList<Integer> mylist =new LinkedList<>();
        mylist.Insert(1);
        String testresulte=mylist.toString();
        assertEquals("{1} -> Null", testresulte);
        mylist.Insert(10);
        mylist.Insert(8);
        String testresulte2=mylist.toString();
        assertEquals("{8} -> {10} -> {1} -> Null", testresulte2);

    }
    @Test void TestIncludeList() {
        LinkedList<Integer> mylist =new LinkedList<>();
        mylist.Insert(1);
        mylist.Insert(10);
        mylist.Insert(8);
        boolean testresulte=mylist.Include(10);
        assertEquals(true, testresulte);
        boolean testresulte2=mylist.Include(5);
        assertEquals(false, testresulte2);

    }
    @Test void TestAllList() {
        LinkedList<Integer> mylist =new LinkedList<>();
        mylist.Insert(1);
        mylist.Insert(10);
        mylist.Insert(8);
        mylist.Insert(9);
        String testresulte=mylist.toString();
        assertEquals("{9} -> {8} -> {10} -> {1} -> Null", testresulte);


    }

}
