/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challange;

public class App {


    public static void main(String[] args) {

    LinkedList<Integer> mylist = new LinkedList<>();
        LinkedList<Integer> mylist2 = new LinkedList<>();
//        System.out.println(mylist.toString());
//        mylist.Insert(1);
////        System.out.println(mylist.toString());
//        mylist.insert(5);
//        mylist.insert(6);
        mylist.Insert(1);
        mylist.Insert(2);
////        mylist.inserlast(66);
        mylist.Insert(8);
        mylist.Insert(5);
        mylist.Insert(60);
        mylist.Insert(11);
        mylist.Insert(15);
                System.out.println(mylist.toString());
        mylist2=mylist;

//        System.out.println(mylist.findNth(3));
//        mylist.Insert(66);
        mylist2.Insert(20);
        System.out.println(mylist.toString());
        System.out.println(mylist2.toString());
       mylist.palindrome();
//        mylist2.Insert(7);
//        mylist2.Insert(4);
//        mylist2.Insert(7);
//        mylist2.Insert(77);
//        mylist2.Insert(8);
//        mylist.Insert(1);
//        mylist.Insert(2);
//        mylist.Insert(3);
//        mylist2.Insert(20);
//        mylist2.Insert(21);
//        mylist2.Insert(22);
//        System.out.println(mylist.toString());
//        System.out.println(mylist2.toString());

//        System.out.println(LinkedList.zipLists(mylist,mylist2));

//        mylist.insertbefore(3,77);
//       mylist.insertafter(10,6);
//        System.out.println(mylist.toString());
//       System.out.println(mylist.Include(10));
//        System.out.println(mylist.Include(3));
//        System.out.println(mylist.kthfromend(4));


//        System.out.println(mylist.reserve());
//        System.out.println(mylist.toString());


//        System.out.println(mylist.kthfromend(3));
//        System.out.println(mylist.toString());


    }
}
