/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challange;

public class App {


    public static void main(String[] args) {

    LinkedList<Integer> mylist = new LinkedList<>();
//        System.out.println(mylist.toString());
        mylist.Insert(1);
        mylist.Insert(5);
        mylist.Insert(70);
//        System.out.println(mylist.toString());

        mylist.insertBefore(70,60);
//       mylist.insertAfter(10,6);
//        mylist.insertAfter(5, 60);
        System.out.println(mylist.toString());
//       System.out.println(mylist.Include(10));
//        System.out.println(mylist.Include(3));




    }
}
