/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void emptyTree() {
        BinaryTree<Integer> pre = new BinaryTree<Integer>();
        Integer correct =pre.getRoot().getValue();
        assertEquals(null, correct);


    }
    @Test void singleRootTree() {
        BinaryTree<Integer> pre = new BinaryTree<Integer>(5);
        Integer correct =pre.getRoot().getValue();
        assertEquals(5, correct);

    }
    @Test void singleRootTreeWithRightAndLeft() {
        BinaryTree<Integer> pre = new BinaryTree<Integer>(5);
        pre.getRoot().setLeft(3);
        pre.getRoot().setRight(2);
        Integer correctLeft =pre.getRoot().getLeft().getValue();
        Integer correctRigth =pre.getRoot().getRight().getValue();
        assertEquals(2, correctRigth);
        assertEquals(3, correctLeft);

    }
    @Test void CollectionFromPreorder() {
        BinarySearchTree binarySearchTree= new BinarySearchTree(5);
        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(8);
        String correct=binarySearchTree.preOrder(binarySearchTree.getRoot());
        String expect="-->5-->2-->7-->8";
        assertEquals(expect, correct);
    }
    @Test void CollectionFromInOrder() {
        BinarySearchTree binarySearchTree= new BinarySearchTree(5);
        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(8);
        String correct=binarySearchTree.inOrder(binarySearchTree.getRoot());
        String expect="-->2-->5-->7-->8";
        assertEquals(expect, correct);
    }
    @Test void CollectionFromPostOrder() {
        BinarySearchTree binarySearchTree= new BinarySearchTree(5);
        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(8);
        String correct=binarySearchTree.PostOrder(binarySearchTree.getRoot());
        String expect="-->2-->8-->7-->5";
        assertEquals(expect, correct);
    }
    @Test void Contain() {
        BinarySearchTree binarySearchTree= new BinarySearchTree(5);
        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(8);
        boolean correct=binarySearchTree.Contains(7);
        boolean expect=true;
        assertEquals(expect, correct);
        boolean correct2=binarySearchTree.Contains(99);
        boolean expect2=false;
        assertEquals(expect2, correct2);
    }
    @Test void Max() {
        BinaryTree<Integer> pre = new BinaryTree<Integer>(5);
        pre.getRoot().setLeft(8);
        pre.getRoot().setRight(6);
        pre.getRoot().setRight(10);
        pre.getRoot().setLeft(99);
        int correct =pre.max();

        assertEquals(99, correct);


    }
    @Test void  breadthFirstTest() {
        BinaryTree binaryTest= new BinaryTree<Integer>(9);
        binaryTest.getRoot().setLeft(4);
        binaryTest.getRoot().setRight(6);
        binaryTest.getRoot().getLeft().setRight(3);

        assertEquals("[9, 4, 6, 3]", binaryTest.breadthFirst());


    }
    @Test

    void oddSumTest(){
      BinarySearchTree  binarySearchTree2=new BinarySearchTree(8);
        binarySearchTree2.Add(3);
        binarySearchTree2.Add(10);
        binarySearchTree2.Add(1);
        binarySearchTree2.Add(6);
        binarySearchTree2.Add(14);
        binarySearchTree2.Add(4);
        binarySearchTree2.Add(7);
        binarySearchTree2.Add(13);
        int sum=0;
        assertEquals(24,binarySearchTree2.oddSum());

    }

}
