/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {
    public static void main(String[] args) {

        BinarySearchTree tree1 = new BinarySearchTree(200);
        tree1.Add(100);
        tree1.Add(250);

        BinarySearchTree tree2 = new BinarySearchTree(200);
        tree2.Add(100);
        tree2.Add(300);
        System.out.println(HashTable.intersection(tree1, tree2));
    }


}
