/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

public class App {


    public static void main(String[] args) {
         HashTable<String,String> hashTable= new HashTable<>();

        hashTable.add("Name2","maiada2");
        System.out.println(hashTable.get("Name2"));
        hashTable.add("Name2","maiada1");
        System.out.println(hashTable.get("Name2"));
    }


}
