/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private HashTable<String,String> hashTable;


    @BeforeEach
    void pickup(){
        hashTable= new HashTable<>();
        hashTable.add("Name","MAIADA");
    }
    // test add
    @Test
    void addTest(){
        assertTrue(hashTable.contain("Name"));
    }
    // test get
    @Test
    void getTest(){
        assertEquals("MAIADA",hashTable.get("Name"));
    }
    // test getnull
    @Test
    void getNullTest(){
        assertEquals(null,hashTable.get("age"));

    }
    @Test
    public void collisionTest() {

        HashTable table = new HashTable();

        // 10 and  100 have the  same hash value of 0
        table.add(10, 99);
        table.add(100, 88);
        assertEquals(99, table.get(10) );
        assertEquals(88, table.get(100) );
    }
    @Test
    public void hashTest() {

        HashTable table = new HashTable();
        int hashValue = table.hash(50);
        assertTrue(hashValue < 30);
    }
//---------------------cc-31


    @Test
    void repeatWordTest(){
        String result= HashTable.repeatedWord("Once upon a time, there was a brave princess who...");
        assertEquals("a",result);
    }

    @Test
    void repeatWordTest2(){
        String result= HashTable.repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...");
        assertEquals("it",result);
    }
    @Test
    void repeatWordTest3(){
        String result= HashTable.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..." );
        assertEquals("summer",result);
    }
}
