/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challange;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void Kth() {
        LinkedList classUnderTest = new LinkedList();
        classUnderTest.Insert(1);
        classUnderTest.Insert(2);
//        mylist.inserlast(66);
        classUnderTest.Insert(3);
        classUnderTest.Insert(4);
        classUnderTest.Insert(5);
        classUnderTest.Insert(66);
         classUnderTest.reserve();
        assertEquals("{66} -> {5} -> {4} -> {3} -> {2} -> {1} -> Null", classUnderTest.reserve());


    }
    @Test void zipList() {
        LinkedList list1 = new LinkedList();
        LinkedList list2 = new LinkedList();
        LinkedList ziplist = new LinkedList();


        list1.Insert(1);
        list1.Insert(2);
        list1.Insert(3);
        list2.Insert(20);
        list2.Insert(21);
        list2.Insert(22);
        assertEquals("{20} -> {1} -> {21} -> {2} -> {22} -> {3} -> Null", LinkedList.zipLists(list1,list2).toString());


    }
}
