/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import java.io.IOException;

public class Library {
    public static void main(String[] args) {

        Stack stack = new Stack();
        stack.push(5);
        stack.push(4);
        stack.push(70);

//        System.out.println(stack);
//        System.out.println(stack.pop());
//        System.out.println(stack);
//        System.out.println(stack.pop());
//        System.out.println(stack);
//        System.out.println(stack.pop().toString());
//        System.out.println(stack);
//        System.out.println(stack.pop().toString());
//        System.out.println(stack);
//         System.out.println(stack.peek());
//                System.out.println(stack.peek().toString());
//
//        Queue queue=new Queue();
//queue.enQueue(5);
//queue.enQueue(4);
//queue.enQueue(70);
//queue.deQueue();
//        queue.deQueue();

//System.out.println(queue.deQueue().toString());

        PseudoQueue<Integer> ps = new PseudoQueue<>();
                 ps.enqueue(5);
                 ps.enqueue(10);
                 ps.enqueue(15);
                 System.out.println(ps.toString());
                 System.out.println(ps.dequeue());


        System.out.println(ps.toString());





    }


    private static class T {
    }
}
