/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

public class App {


    public static void main(String[] args) {
//        Node<Integer> root=new Node<Integer>(5);

//        BinaryTree<Integer> pre = new BinaryTree<Integer>();
//        pre.getRoot().setLeft(3);
//        pre.getRoot().setRight(2);
//        pre.getRoot().getLeft().setRight(1);
//        System.out.println( pre.getRoot().getValue());
//        System.out.println(pre.getRoot().getRight().getValue());
        BinarySearchTree binarySearchTree= new BinarySearchTree(5);
//        BinaryTree<Integer> pre = new BinaryTree<Integer>(binarySearchTree);
        binarySearchTree.Add(2);
        binarySearchTree.Add(7);
        binarySearchTree.Add(8);
//System.out.println(binarySearchTree.inOrder(binarySearchTree.getRoot()));
//System.out.println(binarySearchTree.PostOrder(binarySearchTree.getRoot()));
//System.out.println(binarySearchTree.preOrder(binarySearchTree.getRoot()));


        System.out.println(binarySearchTree.Contains(7));



    }
}
