/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

public class App {


    public static void main(String[] args) {

    LinkedList<Integer> mylist = new LinkedList<>();
        System.out.println(mylist.toString());
        mylist.insert(1);
        System.out.println(mylist.toString());
//        mylist.insert(5);
//        mylist.insert(6);
        mylist.insert(10);
        mylist.insert(8);
        mylist.insert(9);
        System.out.println(mylist.toString());
       System.out.println(mylist.include(10));
        System.out.println(mylist.include(3));




    }
}
